#!/usr/bin/env ruby

require "bundler/setup"
require "led_badge"
require "thor"

class CLI < Thor

  desc "set_message MESSAGE", "Set a single message"
  def set_message(message)
    badge = LedBadge::Badge.new
    badge.set_message(message)
  end

  desc "run_server", "Run REST server"
  method_option :bind, default: "0.0.0.0"
  method_option :port, type: :numeric, default: 9292
  method_option :debug, type: :boolean, default: false
  def run_server
    LedBadge.run_server(options)
  end

end

CLI .start
